spring:
  datasource:
    url:
    username:  # Update with your PostgreSQL username
    password:   # Update with your PostgreSQL password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for dev environment to automatically update schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Change dialect for PostgreSQL
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
