spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Update schema for testing
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
